language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/jgnewman/ci/master/build-package.sh | sh'

git:
  depth: 10

branches:
  only:
    - master
